
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jesus Cueva
 */
public class DatosTabla extends javax.swing.JFrame {

    int cont = 1;
    
    /**
     * Creates new form DatosTabla
     */
    public DatosTabla() {
        initComponents();
        
        campo2.setVisible(false);
        campo3.setVisible(false);
        campo4.setVisible(false);
        campo5.setVisible(false);
        tipo2.setVisible(false);
        tipo3.setVisible(false);
        tipo4.setVisible(false);
        tipo5.setVisible(false);
        tamano1.setVisible(false);
        tamano2.setVisible(false);
        tamano3.setVisible(false);
        tamano4.setVisible(false);
        tamano5.setVisible(false);
        
    }

    public void probando(){
        
        if(cont == 2){
            campo2.setVisible(true);
            tipo2.setVisible(true);
        }else if(cont == 3){
            campo3.setVisible(true);
            tipo3.setVisible(true);
        }else if(cont == 4){
            campo4.setVisible(true);
            tipo4.setVisible(true);
        }else if(cont == 5){
            campo5.setVisible(true);
            tipo5.setVisible(true);
        }
        
    }
            
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campo1 = new javax.swing.JTextField();
        campo2 = new javax.swing.JTextField();
        campo3 = new javax.swing.JTextField();
        campo4 = new javax.swing.JTextField();
        campo5 = new javax.swing.JTextField();
        tipo1 = new javax.swing.JComboBox<>();
        tipo2 = new javax.swing.JComboBox<>();
        tipo3 = new javax.swing.JComboBox<>();
        tipo4 = new javax.swing.JComboBox<>();
        tipo5 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        nombreTabla = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        tamano1 = new javax.swing.JSpinner();
        tamano2 = new javax.swing.JSpinner();
        tamano3 = new javax.swing.JSpinner();
        tamano4 = new javax.swing.JSpinner();
        tamano5 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Ingresa los datos de la tabla");

        jLabel2.setText("Campo 1: ");

        jLabel3.setText("Nota*: No es necesario añadir un ID en estos campos. Este se creara automaticamente. ");

        jLabel4.setText("Campo 2: ");

        jLabel5.setText("Campo 3: ");

        jLabel6.setText("Campo 4: ");

        jLabel7.setText("Campo 5:");

        jLabel8.setText("Tipo");

        tipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INTEGER", "VARCHAR", "TIMESTAMP", "DECIMAL", "FLOAT", "BOOLEAN" }));
        tipo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tipo1MouseClicked(evt);
            }
        });
        tipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo1ActionPerformed(evt);
            }
        });

        tipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INTEGER", "VARCHAR", "TIMESTAMP", "DECIMAL", "FLOAT", "BOOLEAN" }));
        tipo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tipo2MouseClicked(evt);
            }
        });
        tipo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo2ActionPerformed(evt);
            }
        });

        tipo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INTEGER", "VARCHAR", "TIMESTAMP", "DECIMAL", "FLOAT", "BOOLEAN" }));
        tipo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo3ActionPerformed(evt);
            }
        });

        tipo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INTEGER", "VARCHAR", "TIMESTAMP", "DECIMAL", "FLOAT", "BOOLEAN" }));
        tipo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo4ActionPerformed(evt);
            }
        });

        tipo5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INTEGER", "VARCHAR", "TIMESTAMP", "DECIMAL", "FLOAT", "BOOLEAN" }));
        tipo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Tamaño");

        jButton1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel10.setText("Ingresa el nombre de la tabla: ");

        jButton3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton3.setText("+");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(nombreTabla, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(272, 272, 272)
                                        .addComponent(jLabel8)))
                                .addGap(115, 115, 115)
                                .addComponent(jLabel9)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(52, 52, 52)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(campo3))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(campo2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(campo5)
                                                    .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tipo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tipo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tipo3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tipo4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tipo5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tamano1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(tamano2)
                                    .addComponent(tamano3)
                                    .addComponent(tamano4)
                                    .addComponent(tamano5))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tamano1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tamano2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tipo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tamano3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tipo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tamano4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tipo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tamano5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo3ActionPerformed
        System.out.println(tipo3.getSelectedItem().toString());
        if(tipo3.getSelectedItem().toString().equals("VARCHAR")){
            System.out.println("entro");
            tamano3.setVisible(true);
        }else if(tipo3.getSelectedItem().toString().equals("FLOAT")){
            tamano3.setVisible(true);
        }else{
            tamano3.setVisible(false);
        }
        
    }//GEN-LAST:event_tipo3ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
        this.dispose();
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        try{

            String myDriver = "org.h2.Driver";
            String myUrl = "jdbc:h2:~/test";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl, "sa", "");
            Statement stmt;
            
            //Aqui saco todas mis variables
            String nombre = nombreTabla.getText();
            String camp1 = campo1.getText();
            String camp2 = campo2.getText();
            String camp3 = campo3.getText();
            String camp4 = campo4.getText();
            String camp5 = campo5.getText();
            String item1 = (String)tipo1.getSelectedItem();
            String item2 = (String)tipo2.getSelectedItem();
            String item3 = (String)tipo3.getSelectedItem();
            String item4 = (String)tipo4.getSelectedItem();
            String item5 = (String)tipo5.getSelectedItem();
            int valor1 = (int) tamano1.getValue();
            int valor2 = (int) tamano2.getValue();
            int valor3 = (int) tamano3.getValue();
            int valor4 = (int) tamano4.getValue();
            int valor5 = (int) tamano5.getValue();
            
            String pk = "id"+nombre;
            stmt = conn.createStatement();
            
            String sql = "Create table "+nombre+" ("+pk+" INTEGER PRIMARY KEY, ";
            if(cont+1 > 1){
                
                if(item1.equals("VARCHAR")){
                    sql=sql+camp1+" "+item1+"("+valor1+")";
                }else if(item1.equals("FLOAT")){
                    sql=sql+camp1+" "+item1+"("+valor1+")";
                }else{
                    sql=sql+camp1+" "+item1;
                }
                
            }
            if(cont+1 > 2){
                
                if(item2.equals("VARCHAR")){
                    sql=sql+", "+camp2+" "+item2+"("+valor2+")";
                }else if(item2.equals("FLOAT")){
                    sql=sql+", "+camp2+" "+item2+"("+valor2+")";
                }else{
                    sql=sql+", "+camp2+" "+item2;
                }
                
            }
            if(cont+1 > 3){
                
                if(item3.equals("VARCHAR")){
                    sql=sql+", "+camp3+" "+item3+"("+valor3+")";
                }else if(item3.equals("FLOAT")){
                    sql=sql+", "+camp3+" "+item3+"("+valor3+")";
                }else{
                    sql=sql+", "+camp3+" "+item3;
                }
                
            }
            if(cont+1 > 4){
                
                if(item4.equals("VARCHAR")){
                    sql=sql+", "+camp4+" "+item4+"("+valor4+")";
                }else if(item2.equals("FLOAT")){
                    sql=sql+", "+camp4+" "+item4+"("+valor4+")";
                }else{
                    sql=sql+", "+camp4+" "+item4;
                }
                
            }
            if(cont+1 > 5){
                
                if(item5.equals("VARCHAR")){
                    sql=sql+", "+camp5+" "+item5+"("+valor5+")";
                }else if(item2.equals("FLOAT")){
                    sql=sql+", "+camp5+" "+item5+"("+valor5+")";
                }else{
                    sql=sql+", "+camp5+" "+item5;
                }
                
            }
            
            System.out.println(sql);
            sql= sql+")";
            stmt.executeUpdate(sql);  
            
            JOptionPane.showMessageDialog(null,"Se ha creado exitosamente la tabla!");
            
            stmt.close();
            conn.close();
            
        }catch (Exception e){

            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
            
        }    
        
        this.dispose();
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       
        cont++;
        probando();
    }//GEN-LAST:event_jButton3MouseClicked

    private void tipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo1ActionPerformed
        
        if(tipo1.getSelectedItem().toString().equals("VARCHAR")){
            tamano1.setVisible(true);
        }else if(tipo1.getSelectedItem().toString().equals("FLOAT")){
            tamano1.setVisible(true);
        }else{
            tamano1.setVisible(false);
        }
        
    }//GEN-LAST:event_tipo1ActionPerformed

    private void tipo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo2ActionPerformed
       
        if(tipo2.getSelectedItem().toString().equals("VARCHAR")){
            tamano2.setVisible(true);
        }else if(tipo2.getSelectedItem().toString().equals("FLOAT")){
            tamano2.setVisible(true);
        }else{
            tamano2.setVisible(false);
        }
        
    }//GEN-LAST:event_tipo2ActionPerformed

    private void tipo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo4ActionPerformed
        
        if(tipo4.getSelectedItem().toString().equals("VARCHAR")){
            tamano4.setVisible(true);
        }else if(tipo4.getSelectedItem().toString().equals("FLOAT")){
            tamano4.setVisible(true);
        }else{
            tamano4.setVisible(false);
        }
        
    }//GEN-LAST:event_tipo4ActionPerformed

    private void tipo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo5ActionPerformed
       
        if(tipo5.getSelectedItem().toString().equals("VARCHAR")){
            tamano5.setVisible(true);
        }else if(tipo5.getSelectedItem().toString().equals("FLOAT")){
            tamano5.setVisible(true);
        }else{
            tamano5.setVisible(false);
        }
        
    }//GEN-LAST:event_tipo5ActionPerformed

    private void tipo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipo1MouseClicked
       
        if(tipo1.getSelectedItem().toString().equals("VARCHAR")){
            tamano1.setVisible(true);
        }else if(tipo1.getSelectedItem().toString().equals("FLOAT")){
            tamano1.setVisible(true);
        }else{
            tamano1.setVisible(false);
        }
        
    }//GEN-LAST:event_tipo1MouseClicked

    private void tipo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipo2MouseClicked

        if(tipo2.getSelectedItem().toString()==("VARCHAR")){
            tamano2.setVisible(true);
        }else if(tipo2.getSelectedItem().toString().equals("FLOAT")){
            tamano2.setVisible(true);
        }else{
            tamano2.setVisible(false);
        }
        
        
    }//GEN-LAST:event_tipo2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo1;
    private javax.swing.JTextField campo2;
    private javax.swing.JTextField campo3;
    private javax.swing.JTextField campo4;
    private javax.swing.JTextField campo5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombreTabla;
    private javax.swing.JSpinner tamano1;
    private javax.swing.JSpinner tamano2;
    private javax.swing.JSpinner tamano3;
    private javax.swing.JSpinner tamano4;
    private javax.swing.JSpinner tamano5;
    private javax.swing.JComboBox<String> tipo1;
    private javax.swing.JComboBox<String> tipo2;
    private javax.swing.JComboBox<String> tipo3;
    private javax.swing.JComboBox<String> tipo4;
    private javax.swing.JComboBox<String> tipo5;
    // End of variables declaration//GEN-END:variables
}
